/**
 * toPemBuggy manually simulates the historical, buggy behaviour of `toPem` prior to v5.3.4.
 * Previously, if `toPem(buffer)` was provided a concatenated DER buffer (containing multiple certificates),
 * it would Base64 encode the entire payload into a single, massive continuous chunk wrapped by a single
 * -----BEGIN CERTIFICATE----- and -----END CERTIFICATE-----.
 * We maintain this method in tests to definitively prove that our fix in `toPem` works, and that
 * `readCertificateChain` can still gracefully unpack files generated by the old buggy logic.
 */
export function toPemBuggy(buffer: Buffer, pemType: string): string {
    const b = buffer.toString("base64");
    const strBody = b.match(/.{1,64}/g)?.join("\n") || "";
    return `-----BEGIN ${pemType}-----\n${strBody}\n-----END ${pemType}-----\n`;
}
